server:
  port: 80

logging:
 config: classpath:logback-spring.xml
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://127.0.0.1:5432/authserverdb
    username: authserver
    password: Abc123++
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
  data:
    redis:
      database: 3
      host: 183.129.217.214
      port: 20192
      password: QAZwsx123++
      timeout: 3000
      jedis:
        pool:
          max-active: 200
          max-idle: 50
          min-idle: 10
          time-between-eviction-runs: 60000
  jpa:
    hibernate:
      ddl-auto: validate
